const content = document.getElementById('page-manager').children[0];
content.parentNode.removeChild(content);
const parent = document.getElementById('page-manager');
const text = document.createElement('h2');
text.innerText = 'Get back to building your dreams!';
parent.appendChild(text);
const image = document.createElement('img');
let source = chrome.extension.getURL('images/image1.jpg');
image.src = source;
parent.appendChild(image);
parent.classList.add('align');
text.classList.add('beautText');